In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [ ]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
df.drop("Id",axis=1)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
x=df.iloc[:,:-1]
x

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [ ]:
y=df.iloc[:,-1]
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test,=train_test_split(x,y,test_size=.3,random_state=42)
x_train

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
81    82            5.5           2.4            3.7           1.0
133  134            6.3           2.8            5.1           1.5
137  138            6.4           3.1            5.5           1.8
75    76            6.6           3.0            4.4           1.4
109  110            7.2           3.6            6.1           2.5
..   ...            ...           ...            ...           ...
71    72            6.1           2.8            4.0           1.3
106  107            4.9           2.5            4.5           1.7
14    15            5.8           4.0            1.2           0.2
92    93            5.8           2.6            4.0           1.2
102  103            7.1           3.0            5.9           2.1

[105 rows x 5 columns]

In [ ]:
y_train

81     Iris-versicolor
133     Iris-virginica
137     Iris-virginica
75     Iris-versicolor
109     Iris-virginica
            ...
71     Iris-versicolor
106     Iris-virginica
14         Iris-setosa
92     Iris-versicolor
102     Iris-virginica
Name: Species, Length: 105, dtype: object

In [ ]:
x_test

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
73    74            6.1           2.8            4.7           1.2
18    19            5.7           3.8            1.7           0.3
118  119            7.7           2.6            6.9           2.3
78    79            6.0           2.9            4.5           1.5
76    77            6.8           2.8            4.8           1.4
31    32            5.4           3.4            1.5           0.4
64    65            5.6           2.9            3.6           1.3
141  142            6.9           3.1            5.1           2.3
68    69            6.2           2.2            4.5           1.5
82    83            5.8           2.7            3.9           1.2
110  111            6.5           3.2            5.1           2.0
12    13            4.8           3.0            1.4           0.1
36    37            5.5           3.5            1.3           0.2
9     10            4.9           3.1            1.5           0.1
19    20            5.1           3.8            1.5           0.3
56    57            6.3           3.3            4.7           1.6
104  105            6.5           3.0            5.8           2.2
69    70            5.6           2.5            3.9           1.1
55    56            5.7           2.8            4.5           1.3
132  133            6.4           2.8            5.6           2.2
29    30            4.7           3.2            1.6           0.2
127  128            6.1           3.0            4.9           1.8
26    27            5.0           3.4            1.6           0.4
128  129            6.4           2.8            5.6           2.1
131  132            7.9           3.8            6.4           2.0
145  146            6.7           3.0            5.2           2.3
108  109            6.7           2.5            5.8           1.8
143  144            6.8           3.2            5.9           2.3
45    46            4.8           3.0            1.4           0.3
30    31            4.8           3.1            1.6           0.2
22    23            4.6           3.6            1.0           0.2
15    16            5.7           4.4            1.5           0.4
65    66            6.7           3.1            4.4           1.4
11    12            4.8           3.4            1.6           0.2
42    43            4.4           3.2            1.3           0.2
146  147            6.3           2.5            5.0           1.9
51    52            6.4           3.2            4.5           1.5
27    28            5.2           3.5            1.5           0.2
4      5            5.0           3.6            1.4           0.2
32    33            5.2           4.1            1.5           0.1
142  143            5.8           2.7            5.1           1.9
85    86            6.0           3.4            4.5           1.6
86    87            6.7           3.1            4.7           1.5
16    17            5.4           3.9            1.3           0.4
10    11            5.4           3.7            1.5           0.2

In [ ]:
y_train

81     Iris-versicolor
133     Iris-virginica
137     Iris-virginica
75     Iris-versicolor
109     Iris-virginica
            ...
71     Iris-versicolor
106     Iris-virginica
14         Iris-setosa
92     Iris-versicolor
102     Iris-virginica
Name: Species, Length: 105, dtype: object

In [ ]:
y_test

73     Iris-versicolor
18         Iris-setosa
118     Iris-virginica
78     Iris-versicolor
76     Iris-versicolor
31         Iris-setosa
64     Iris-versicolor
141     Iris-virginica
68     Iris-versicolor
82     Iris-versicolor
110     Iris-virginica
12         Iris-setosa
36         Iris-setosa
9          Iris-setosa
19         Iris-setosa
56     Iris-versicolor
104     Iris-virginica
69     Iris-versicolor
55     Iris-versicolor
132     Iris-virginica
29         Iris-setosa
127     Iris-virginica
26         Iris-setosa
128     Iris-virginica
131     Iris-virginica
145     Iris-virginica
108     Iris-virginica
143     Iris-virginica
45         Iris-setosa
30         Iris-setosa
22         Iris-setosa
15         Iris-setosa
65     Iris-versicolor
11         Iris-setosa
42         Iris-setosa
146     Iris-virginica
51     Iris-versicolor
27         Iris-setosa
4          Iris-setosa
32         Iris-setosa
142     Iris-virginica
85     Iris-versicolor
86     Iris-versicolor
16         Iris-setosa
10         Iris-setosa
Name: Species, dtype: object

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=5)
model.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test,=train_test_split(x,y,test_size=.3,random_state=42)
model.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.fit_transform(x_train)
x_test=scalar.fit_transform(x_test)
x_train

array([[ 0.07890874, -0.4134164 , -1.46440146, -0.10014569, -0.32149987],
       [ 1.32052747,  0.55122187, -0.49582097,  0.71771076,  0.35364985],
       [ 1.41603661,  0.67180165,  0.2306144 ,  0.95138404,  0.75873969],
       [-0.06435496,  0.91296121, -0.01153072,  0.30878254,  0.21861991],
       [ 0.74747267,  1.63643991,  1.44134002,  1.30189395,  1.7039493 ],
       [ 0.43706799, -0.17225683, -0.25367584,  0.1919459 ,  0.08358997],
       [ 0.65196354,  2.11875905, -0.01153072,  1.59398554,  1.16382952],
       [-0.27925051, -0.29283662, -0.01153072,  0.36720086,  0.35364985],
       [-1.85515122, -0.89573553,  1.19919489, -1.443767  , -1.40173942],
       [ 1.05787735,  2.23933883, -0.49582097,  1.65240385,  1.02879957],
       [-0.25537323, -0.05167705, -0.73796609,  0.13352758, -0.32149987],
       [-1.18658728, -0.77515575,  0.95704977, -1.443767  , -1.40173942],
       [-0.90005988, -1.01631531,  1.19919489, -1.50218532, -1.26670948],
       [-0.80455075, -0.89573553,  1.92563026, -1.15167541, -1.13167953],
       [-0.42251421, -1.01631531, -2.43298195, -0.21698232, -0.32149987],
       [ 1.08175464,  0.55122187, -0.73796609,  0.60087413,  0.75873969],
       [-1.28209642, -1.25747488,  0.95704977, -1.15167541, -1.40173942],
       [-1.25821913, -1.01631531, -0.01153072, -1.32693037, -1.40173942],
       [-1.3059737 , -0.89573553,  0.71490465, -1.26851205, -0.99664959],
       [ 0.38931342, -0.29283662, -0.73796609,  0.1919459 ,  0.08358997],
       [-0.92393717, -0.89573553,  0.95704977, -1.38534869, -1.40173942],
       [ 0.4131907 , -0.17225683, -0.01153072,  0.1919459 , -0.05143998],
       [ 0.93849094,  2.23933883,  1.92563026,  1.65240385,  1.29885946],
       [-0.7329189 , -1.49863445,  0.47275953, -1.443767  , -1.40173942],
       [ 0.46094527,  0.43064208, -0.25367584,  0.25036422,  0.08358997],
       [ 0.8429818 , -0.17225683, -1.22225633,  0.65929245,  1.02879957],
       [-1.06720087, -0.4134164 ,  2.89421075, -1.443767  , -1.40173942],
       [ 1.43991389,  0.18948252, -0.01153072,  0.54245581,  0.75873969],
       [ 0.5564544 , -0.05167705, -0.73796609,  0.71771076,  0.89376963],
       [-0.37475965,  0.18948252, -1.9486917 ,  0.07510927, -0.32149987],
       [ 0.15054059, -0.53399618, -0.01153072,  0.36720086,  0.35364985],
       [ 1.67868672,  0.43064208,  0.95704977,  0.89296572,  1.43388941],
       [-0.5896552 , -0.4134164 , -1.70654658,  0.07510927,  0.08358997],
       [-1.7357648 , -0.53399618,  2.16777538, -1.26851205, -1.13167953],
       [ 0.36543614, -1.01631531, -1.70654658, -0.33381896, -0.32149987],
       [ 0.79522724,  0.67180165, -0.73796609,  0.8345474 ,  0.89376963],
       [-0.68516433, -1.01631531,  0.71490465, -1.443767  , -1.40173942],
       [-1.0194463 , -1.01631531,  0.47275953, -1.56060364, -1.40173942],
       [ 0.05503145, -0.4134164 , -1.46440146, -0.04172737, -0.18646992],
       [-0.0166004 ,  1.033541  , -0.01153072,  0.65929245,  0.62370974],
       [-1.04332358, -1.1368951 ,  0.2306144 , -1.38534869, -1.53676936],
       [ 0.86685909, -0.05167705, -0.49582097,  0.71771076,  1.56891935],
       [-1.68801023, -1.01631531,  0.95704977, -1.38534869, -1.40173942],
       [-0.82842803, -1.01631531,  1.19919489, -1.32693037, -0.86161964],
       [-0.18374138,  0.06890273,  0.47275953,  0.54245581,  0.75873969],
       [ 0.48482255, -0.89573553, -1.22225633, -0.50907391, -0.18646992],
       [ 1.01012279,  1.27470056,  0.47275953,  1.06822067,  1.43388941],
       [ 0.1266633 ,  0.18948252, -0.73796609,  0.71771076,  0.4886798 ],
       [ 1.34440475,  0.3100623 , -0.98011121,  1.00980236,  0.21861991],
       [ 1.36828204,  2.23933883, -0.01153072,  1.30189395,  1.43388941],
       [ 0.269927  , -0.4134164 , -1.22225633,  0.07510927,  0.08358997],
       [-1.66413295, -1.73979401, -0.25367584, -1.443767  , -1.40173942],
       [-1.54474653, -1.8603738 , -0.01153072, -1.61902196, -1.53676936],
       [ 0.9862455 ,  0.18948252, -1.9486917 ,  0.65929245,  0.35364985],
       [ 1.1295092 ,  1.63643991,  0.47275953,  1.24347563,  0.75873969],
       [-1.78351937, -1.49863445,  0.2306144 , -1.38534869, -1.40173942],
       [-1.4492374 , -0.89573553,  1.19919489, -1.443767  , -1.26670948],
       [-0.94781445, -1.73979401, -0.01153072, -1.50218532, -1.40173942],
       [-0.13598681,  0.55122187, -1.22225633,  0.60087413,  0.35364985],
       [ 1.39215932,  0.55122187,  0.95704977,  1.00980236,  1.56891935],
       [-1.71188752, -1.49863445,  0.95704977, -1.443767  , -1.26670948],
       [ 0.81910452,  1.15412078, -0.01153072,  0.95138404,  1.16382952],
       [ 0.53257712,  0.55122187,  0.71490465,  1.24347563,  1.7039493 ],
       [-1.80739665, -1.37805466,  0.47275953, -1.50218532, -1.40173942],
       [-0.35088236,  0.3100623 , -0.25367584,  0.48403749,  0.21861991],
       [-0.56577791,  0.79238143, -0.49582097,  0.42561917,  0.35364985],
       [ 1.15338649,  0.43064208, -0.49582097,  0.54245581,  0.75873969],
       [-0.66128705,  1.39528035,  0.47275953,  0.48403749,  0.21861991],
       [ 0.89073637,  0.67180165,  0.47275953,  0.8345474 ,  1.43388941],
       [-0.75679618, -0.89573553,  1.92563026, -1.32693037, -1.40173942],
       [ 1.46379117,  1.27470056,  0.2306144 ,  0.89296572,  1.16382952],
       [-0.39863693,  0.06890273, -0.01153072,  0.1919459 ,  0.35364985],
       [ 1.65480944,  0.79238143, -0.01153072,  0.77612908,  1.02879957],
       [ 0.03115417, -0.17225683, -0.98011121, -0.21698232, -0.32149987],
       [-0.4463915 , -0.77515575, -0.73796609,  0.01669095,  0.21861991],
       [ 0.31768157,  0.3100623 , -0.01153072,  0.42561917,  0.21861991],
       [-0.8761826 , -1.61921423, -1.70654658, -1.50218532, -1.26670948],
       [-0.47026878,  0.91296121, -0.25367584,  0.42561917,  0.08358997],
       [ 0.29380429, -0.4134164 , -0.98011121,  0.30878254, -0.05143998],
       [-0.70904161, -0.65457597,  1.68348514, -1.38534869, -1.40173942],
       [ 0.24604972, -0.29283662, -0.01153072,  0.13352758,  0.08358997],
       [ 0.6997181 ,  1.7570197 , -0.25367584,  1.41873058,  0.75873969],
       [ 1.10563192,  1.033541  ,  0.71490465,  1.06822067,  1.16382952],
       [-1.35372827, -0.89573553,  1.68348514, -1.38534869, -1.13167953],
       [-0.49414606, -1.1368951 , -1.46440146, -0.33381896, -0.32149987],
       [ 1.58317759,  1.033541  ,  0.71490465,  1.06822067,  1.7039493 ],
       [ 1.22501834,  1.63643991, -0.01153072,  1.12663899,  0.4886798 ],
       [-0.97169173, -1.1368951 ,  0.2306144 , -1.38534869, -1.53676936],
       [ 1.48766846,  1.033541  ,  0.2306144 ,  1.00980236,  1.56891935],
       [-1.83127393, -1.1368951 , -0.01153072, -1.443767  , -1.40173942],
       [-0.61353248,  1.27470056,  0.2306144 ,  0.60087413,  0.35364985],
       [ 1.24889562,  1.87759948, -0.49582097,  1.30189395,  0.89376963],
       [ 0.60420897,  0.55122187, -0.25367584,  1.00980236,  0.75873969],
       [ 0.50869984, -0.17225683, -0.49582097,  0.13352758,  0.08358997],
       [ 0.91461365,  0.79238143, -0.01153072,  0.95138404,  0.75873969],
       [ 0.22217244,  0.55122187, -1.70654658,  0.30878254,  0.08358997],
       [-0.08823225,  0.67180165, -0.25367584,  0.25036422,  0.08358997],
       [ 1.03400007, -0.29283662, -0.49582097,  0.60087413,  1.02879957],
       [ 1.70256401,  0.06890273, -0.01153072,  0.71771076,  0.75873969],
       [-1.37760555, -0.53399618,  0.95704977, -1.26851205, -1.40173942],
       [-0.1598641 ,  0.3100623 , -0.49582097,  0.07510927,  0.08358997],
       [ 0.67584082, -1.1368951 , -1.22225633,  0.36720086,  0.62370974],
       [-1.52086925, -0.05167705,  2.40992051, -1.56060364, -1.40173942],
       [ 0.34155885, -0.05167705, -0.98011121,  0.07510927, -0.05143998],
       [ 0.58033169,  1.51586013, -0.01153072,  1.18505731,  1.16382952]])

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred=model.predict(x_test)
y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype='<U15')

In [ ]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)
print(score)

0.9777777777777777